/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mcwpggfgznyhmgmhvlmd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jd3BnZ2Znem55aG1nbWh2bG1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU0NDk4MTAsImV4cCI6MjA4MTAyNTgxMH0.8Wczt4elM2Xkxj0yx0Wbd9bRuA-hJQWufVvUC7iPE-w"

